<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Human extends Model
{
    use HasFactory;
    use LogsActivity;

    protected $fillable = ['is_orphan', 'notes', 'status', 'father_id', 'mother_id', 'passport', 'region', 'state', 'nation',
        'middle_name', 'first_name', 'last_name', 'gender', 'birthday'];

    protected static $logAttributes = ['is_orphan', 'notes', 'status', 'father_id', 'mother_id', 'passport', 'region', 'state', 'nation',
        'middle_name', 'first_name', 'last_name', 'gender', 'birthday'];

    const STATUS_BIRTH = 'birth';
    const STATUS_NEW_NAME = 'new-name';
    const STATUS_CHECK = 'check';

    const STATUS_CHILD = 'child';
    const STATUS_ORPHAN = 'orphan';
    const STATUS_PARENT = 'parent';

    const GENDER_MALE = 2;
    const GENDER_FEMALE = 1;

    protected $casts = [
        'birthday' => 'date',
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::addGlobalScope(function ($query) {
            $query->orderBy('id', 'desc');
        });
    }

    public static function genders()
    {
        return [
            self::GENDER_FEMALE,
            self::GENDER_MALE,
        ];
    }


    public static function statuses()
    {
        return [
            self::STATUS_BIRTH,
            self::STATUS_NEW_NAME,
            self::STATUS_CHECK,
            self::STATUS_CHILD,
            self::STATUS_ORPHAN,
            self::STATUS_PARENT,
        ];
    }

    public function scopeStatusCheck($query)
    {
        $query->where('status', self::STATUS_CHECK);
    }

    public function scopeIsOrphan($query)
    {
        $query->where('is_orphan', 1);
    }


    public function isGenderFemale()
    {
        return $this->gender == self::GENDER_FEMALE;
    }

    public function isGenderMale()
    {
        return $this->gender == self::GENDER_MALE;
    }



    public function user()
    {
        return $this->hasOne(User::class, 'human_id');
    }

    public static function getNewNumber(int $year = null): string
    {
        $year = $year ?? now()->year;
        $number = 1;
        $last = Human::query()->where('number', 'like', $year.'%')->latest()->first();
        if ($last) $number = (int)str_replace($year.'-', '', $last->number)+1;
        return $year.'-'.$number;
    }

    public static function getNewNin(int $year = null): string
    {
        $year = $year ?? now()->year;
        $number = 1;
        $last = Human::query()->where('number', 'like', $year.'%')->latest()->first();
        if ($last) $number = (int)str_replace($year.'-', '', $last->number)+1;
        return $year.'-'.$number;
    }

    public function numberArray():array
    {
        $number = $this->number;
        $number = explode('-',$number);
        $number[1] = sprintf('%04d',$number[1]);
        return $number;
    }

    public function number(): string
    {
        $numbers = $this->numberArray();
        return $numbers[0].'-'.$numbers[1];
    }

    public function nin(): string
    {
        $number = $this->numberArray()[1];
        return $this->birthday->format("d.m.Y").$this->gender.$number;
    }

    public function mother()
    {
        return $this->belongsTo(self::class, 'mother_id');
    }

    public function motherId()
    {
        return $this->mother();
    }

    public function father()
    {
        return $this->belongsTo(self::class, 'father_id');
    }

    public function fatherId()
    {
        return $this->father();
    }

    public function children()
    {
        return $this->hasMany(self::class, 'father_id')
            ->orWhere('mother_id', $this->id);
    }

    public function getFullNameAttribute()
    {
        return $this->last_name .' '. ($this->first_name ?? '[noname]').' '. $this->middle_name;
    }

    public function isStatusNewNameExpired()
    {
        return $this->updated_at->addHours(5)->isBefore(now());
    }

    public function isStatusNewName(): bool
    {
        return $this->status === self::STATUS_NEW_NAME;
    }

    public function isStatusBirth(): bool
    {
        return $this->status === self::STATUS_BIRTH;
    }

    public function isStatusOrphan(): bool
    {
        return $this->status === self::STATUS_ORPHAN;
    }

    public function isStatusCheck(): bool
    {
        return $this->status === self::STATUS_CHECK;
    }

    public function isStatus(): bool
    {
        return $this->status === self::STATUS_CHECK;
    }

    public function updateMiddleName(bool $canBeNull = true, string $optionalFatherName = null)
    {
        if ($this->isGenderFemale()) $postfix = 'wna';
        else $postfix = 'wiç';
        $fatherName = $optionalFatherName ?? optional($this->father)->first_name;
        if (!$fatherName) {
            if ($canBeNull) $this->middle_name = null;
            else throw new \DomainException('Middle name will be empty');
        } else {
            if (in_array(strtolower(substr($fatherName, -1)), ['a', 'e', 'i', 'o', 'u', 'y', 'ä', 'ü', 'ö',]))
                $glue = 'ýe';
            else
                $glue = 'o';
            $this->middle_name = $fatherName.$glue.$postfix;
        }
        $this->save();
    }

    public function updateLastName(bool $canBeNull = true, string $optionalLastName = null)
    {
        if ($this->isGenderFemale()) $postfix = 'wa';
        else $postfix = 'w';
        $lastName = $optionalLastName ?? optional($this->father)->last_name;
        $lastName = substr($lastName,0,-1);
        if (!$lastName) {
            if ($canBeNull) $this->last_name = null;
            else throw new \DomainException('Last name will be empty');
        } else {
            $this->last_name = $lastName.$postfix;
        }
        $this->save();
    }

    public function documents()
    {
        return $this->hasMany(Document::class, 'human_id');
    }

    public function isBCExists()
    {
//        dd($this->getBCFilePath());
        return file_exists($this->getBCFilePath());
    }

    public function getBCFilePath()
    {
        return storage_path('./bc/'.$this->id.'.docx');
    }

    public function toString(): string
    {
        dd($this->full_name);
        return $this->full_name;
    }
}
